name: Publish Changed NuGet Packages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Get list of changed csproj files
        id: changed-projects
        run: |
          echo "Detecting changed csproj files..."
          git fetch --prune --unshallow || true

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            # PR event: karşılaştırılan branch ile base branch arasındaki fark
            git diff --name-only origin/${{ github.event.pull_request.base.ref }}...${{ github.sha }} | grep '\.csproj$' || true
          else
            # Push event: önceki commit ile karşılaştır
            git diff --name-only HEAD^ HEAD | grep '\.csproj$' || true
          fi > changed.txt

          echo "::set-output name=projects::$(cat changed.txt | tr '\n' ' ')"

      - name: Pack and Push Changed Packages
        if: steps.changed-projects.outputs.projects != ''
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          echo "Changed projects to pack and push:"
          echo "${{ steps.changed-projects.outputs.projects }}"

          for proj in ${{ steps.changed-projects.outputs.projects }}
          do
            echo "Packing $proj"
            dotnet pack "$proj" --configuration Release --no-build --output ./nupkgs

            nupkg_file=$(ls ./nupkgs/*.nupkg | head -n 1)
            echo "Pushing $nupkg_file"
            dotnet nuget push "$nupkg_file" --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json --skip-duplicate
            rm ./nupkgs/*.nupkg
          done
